### PR TITLE
Dev/krcah - Completed implementation of Krcah method

### PR DESCRIPTION
**Pull request by Besler**
This one is a lot of code, sorry.

Basically, there is a parameter estimation filter and a functor filter. There is some magic (see ProcessObject) to make the parameter selection method automatic but still work in the two-stage pipeline.

I have also added a test and the results are amazing. Here are what those results look like:
screen shot 2017-11-28 at 01 02 54

This is tested with the input data from https://github.com/Besler/ITKGraphCutSegmentation/tree/master/data/test

There are a few bug fixes and improved documentation where I missed it.

### CODE REVIEW

**Comment by Besler** [comment]
I see what you're saying. I followed the example of itkStatisticsImageFilter[.h](https://github.com/InsightSoftwareConsortium/ITK/blob/6883e0007ee69e0c8fd9afde79c56fa052e699d7/Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h), [.hxx](https://github.com/InsightSoftwareConsortium/ITK/blob/6883e0007ee69e0c8fd9afde79c56fa052e699d7/Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.hxx).

I then followed the example where they use `GetMeanOutput` to cascade two filters together. They use the mean of the statistics filter to do the binary thresholding. See [this example](https://github.com/InsightSoftwareConsortium/ITK/blob/30206c0ec0cfecb6df9dec22e9a54e98463189db/Modules/Filtering/Thresholding/test/itkBinaryThresholdImageFilterTest2.cxx).

Think of it this way: if you setup a pipeline for a bunch of image filters WITHOUT calling `Update()`, you delete a middle filter, and call `Update`, what happens?

**Comment by araex** [comment]
Githubs comment layout is kinda confusing on mobile - I'm not sure what you responded to.

But I don't know how the pipeline behaves in this case - I would expect either an exception because the input cannot be updated or some mechanism kicks in that reconfigures the pipeline automagically. Does the Graft change the behaviour in any way?

I don't understand the need for the Graft, couldn't you just pass GetInput to SetInput of the parameter estimation filter? But if it is needed, why do you need the const_cast? What does non const Graft do? copy metadata and take ownership of the data? I can't find a non const overload for Graft in the itk doxygen. But I'm on mobile, so I might have missed it.

**Comment by Besler** [comment]
I looked into the [code](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkImageSource.hxx). Graft calls the Graft method of the derived DataObject class. For itkImage, this assigns the pixel container.
```c++
void ImageSource::GraftOutput(const DataObjectIdentifierType & key, DataObject *graft)
{
  if ( !graft )
    {
    itkExceptionMacro(<< "Requested to graft output that is a ITK_NULLPTR pointer");
    }

  // we use the process object method since all out output may not be
  // of the same type
  DataObject *output = this->ProcessObject::GetOutput(key);

  // Call GraftImage to copy meta-information, regions, and the pixel container
  output->Graft(graft);
}
```

Internally, the datatype is not defined const. Otherwise, we wouldn't be able to edit the image data. The call sequence is:
```c++
const TInputImage * ImageToImageFilter::GetInput(void) const
{
  return itkDynamicCastInDebugMode< const TInputImage * >( this->GetPrimaryInput() );
} 
DataObject * ProcessObject::GetPrimaryInput()
{
  return m_IndexedInputs[0]->second;
}
```
We have a non-cast point, cast to const, uncast from const. I think `GetInput` returns a pointer to a const member to prevent users from modifying the object but allow developers to still modify.

The heuristic I am going with is, "the very intelligent ITK people do this so there must be a reason".

**Comment by araex** [comment]
This is GraftOutput which actually does take ownership of the image data so it does need a non const pointer in order to change the other image pointer to non owning. But I commented on the usage of the ItkImage Graft method which doesn't do that.

So I think you either need to change it to GraftOutput if you want that behaviour or the const_cast is unnecessary.

**Comment by Besler** [comment]
I'm a little lost, sorry. It looks like `Image::Graft` also uses `const_cast`.
```c++
template< typename TPixel, unsigned int VImageDimension >
void
Image< TPixel, VImageDimension >
::Graft(const Self *image)
{
  // call the superclass' implementation
  Superclass::Graft(image);

  if ( image )
    {
      // Now copy anything remaining that is needed
      this->SetPixelContainer( const_cast< PixelContainer * >
                               ( image->GetPixelContainer() ) );
    }
}
```

To me, these look the same. `GraftOutput` checks if the pointer is null, grabs the image, calls `Graft`. The second does all that work explicitly, 

Does the use of `const_cast` seem wrong in this case?

I tried the following and got an error about converting from SmartPointer to DataObject.
```c++
AllocateOutputs()
{
  InputImageConstPointer image = this->GetInput();
  this->GraftOutput(this->MakeNameFromOutputIndex(0), image);
}
```

This `const_cast` is everywhere in the itk code base. You get final say though.

**Comment by araex** [comment]
Alright, I'll have to look into this as I don't understand why this is necessary. I might well be that it is, but usually a const_cast indicates a design flaw.

In my comment however I was referencing this:
`template< typename TInputImage, typename TOutputImage, typename TMaskImage >
void
KrcahEigenToScalarImageFilter< TInputImage, TOutputImage, TMaskImage >
::GenerateData()
{
  /* Get input */
  typename TInputImage::Pointer input = TInputImage::New();
  input->Graft( const_cast< TInputImage * >( this->GetInput() ));`
Where the const_cast doesn't do anything as Graft apparently does that internally.

Not a pressing matter, I'll look into it when I find the time to do so.

**Comment by Besler** [comment]
Good point. The ITK Software Guide (Book 1) includes this method for designing compositional filter.
```c++
template< typename TImage >
void
CompositeExampleImageFilter< TImage >
::GenerateData()
{
typename ImageType::Pointer input = ImageType::New();
input->Graft( const_cast< ImageType * >( this->GetInput() ));
m_GradientFilter->SetInput( input );
m_ThresholdFilter->ThresholdBelow( this->m_Threshold );
m_RescaleFilter->GraftOutput( this->GetOutput() );
m_RescaleFilter->Update();
this->GraftOutput( m_RescaleFilter->GetOutput() );
}
```

I will ask on the ITK discord.

**Comment by Besler** [comment]
I just read the following line in [itkImageRegistrationMethod.hxx](https://github.com/hinerm/ITK/blob/master/Modules/Registration/Common/include/itkImageRegistrationMethod.hxx):
```c++
template< typename TFixedImage, typename TMovingImage >
void
ImageRegistrationMethod< TFixedImage, TMovingImage >
::SetFixedImage(const FixedImageType *fixedImage)
{
  itkDebugMacro("setting Fixed Image to " << fixedImage);

  if ( this->m_FixedImage.GetPointer() != fixedImage )
    {
    this->m_FixedImage = fixedImage;

    // Process object is not const-correct so the const_cast is required here
    this->ProcessObject::SetNthInput( 0,
                                      const_cast< FixedImageType * >( fixedImage ) );

    this->Modified();
    }
}
```

Notice the comment "Process object is not const-correct". I think you're right, it's a design flaw probably caused by legacy code. When ITK was developed they probably didn't implement `ProcessObject` as a const-correct class. When they realized the error, they probably decided to fix new classes rather than fix `ProcessObject` and potentially break a bunch of code others had written.

**Comment by Besler** [comment]
The build is failing because of something with the python packages now. I'll look into fixing it.

Discourse chat about const_cast: https://discourse.itk.org/t/why-is-const-cast-used-inside-filters/462

**Comment by Besler** [comment]
Even though the Python wrapping is failing, I am going to merge this so I can continue. The repository is moving to https://github.com/InsightSoftwareConsortium/ITKBoneEnhancement.

Bryce

**Pull request merged**
