### PR TITLE
ENH: big merge

### LINKED ISSUE #8: Incorporate various bug fixes from @thewtex
You can find these fixes at https://github.com/Besler/ITK-KrcahSheetnessImageFilter/compare/master...thewtex:module

### LINKED ISSUE #9: Double check the request region for MultiScaleHessianEnhancementImageFilter
Be certain that the requested region for MultiScaleHessianEnhancementImageFilter is correct for the various filters it composes. Currently, the parameter estimation filters all require the largest possible region. MultiScaleHessianEnhancementImageFilter should do the same then too.

### LINKED ISSUE #14: Update the module description
Update the README.md file. The module is not actually empty, and actually looks a great value addition to ITK.

### PR DESCRIPTION
**Pull request by dzenanz**
This is a merge of two development branches with quick and dirty conflict resolution. Requesting feedback. I didn't take a good look at the code, and whether large or important changes were lost due to file renames. @Besler @jhlegarreta @thewtex @phcerdan

Closes #12. Fixes #14. Fixes #9. Fixes #8.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
No objections to it being merged. Thanks for the hard work @dzenanz .

If these commits solve any of the issues opened, may be the concerned ones could be closed modifying the PR message.

**Comment by dzenanz** [comment]
@Besler I don't have permission to merge to this repo, it would be good if you did it. This completely synchronizes your repo and ITK fork.

**Comment by Besler** [comment]
Thank you for the excellent work, @dzenanz!

**Comment by dzenanz** [comment]
I force-pushed the same commit which exists in InsightSoftwareConsortium's fork. Now the repositories are fully synchronized, with the exact same SHA-1 hash.

**Comment by dzenanz** [comment]
And thanks for giving me write permission!

**Pull request merged**
